enable windows builds

diff --git a/.github/workflows/_build.yaml b/.github/workflows/_build.yaml
--- a/.github/workflows/_build.yaml
+++ b/.github/workflows/_build.yaml
@@ -38,5 +38,17 @@ jobs:
       - name: Build the package
         run: python -m build --outdir .
 
-      - name: Install the package
+      - name: Install the package on Linux or MacOS
+        if: runner.os != 'Windows'
         run: python -m pip install python_kraken_sdk*.whl
+
+      - name: Install the package on Windows
+        if: runner.os == 'Windows'
+        run: |
+          try {
+              $WHEEL = Get-ChildItem -Path . -Filter "python_kraken_sdk*.whl" -ErrorAction Stop
+              python -m pip install $WHEEL
+          } catch {
+              Write-Error "Error: .whl file not found in the current directory."
+              exit 1
+          }
